import type { Metadata } from "next"; 
import { Toaster } from "react-hot-toast";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className="antialiased bg-gray-100 text-gray-800">
        <Header />
        <main className="max-w-6xl mx-auto p-6 min-h-[70vh]">{children}</main>
        <Toaster position="top-center" reverseOrder={false} />
        <Footer />
      </body>

    </html>
  );
}
